language: node_js
node_js: 
    - "3.3.1"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - npm install
script:
    - gulp
after_script:
    - echo "Build executed!"
